// Code generated by protoc-gen-go. DO NOT EDIT.
// source: replica.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{0}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type UpdateValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Prev                 string   `protobuf:"bytes,3,opt,name=prev,proto3" json:"prev,omitempty"`
	Clock                int32    `protobuf:"varint,4,opt,name=clock,proto3" json:"clock,omitempty"`
	ID                   int32    `protobuf:"varint,5,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateValue) Reset()         { *m = UpdateValue{} }
func (m *UpdateValue) String() string { return proto.CompactTextString(m) }
func (*UpdateValue) ProtoMessage()    {}
func (*UpdateValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{1}
}

func (m *UpdateValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateValue.Unmarshal(m, b)
}
func (m *UpdateValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateValue.Marshal(b, m, deterministic)
}
func (m *UpdateValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateValue.Merge(m, src)
}
func (m *UpdateValue) XXX_Size() int {
	return xxx_messageInfo_UpdateValue.Size(m)
}
func (m *UpdateValue) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateValue.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateValue proto.InternalMessageInfo

func (m *UpdateValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *UpdateValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *UpdateValue) GetPrev() string {
	if m != nil {
		return m.Prev
	}
	return ""
}

func (m *UpdateValue) GetClock() int32 {
	if m != nil {
		return m.Clock
	}
	return 0
}

func (m *UpdateValue) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type Verify struct {
	Vertices             []string `protobuf:"bytes,1,rep,name=vertices,proto3" json:"vertices,omitempty"`
	ID                   int32    `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Verify) Reset()         { *m = Verify{} }
func (m *Verify) String() string { return proto.CompactTextString(m) }
func (*Verify) ProtoMessage()    {}
func (*Verify) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{2}
}

func (m *Verify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Verify.Unmarshal(m, b)
}
func (m *Verify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Verify.Marshal(b, m, deterministic)
}
func (m *Verify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Verify.Merge(m, src)
}
func (m *Verify) XXX_Size() int {
	return xxx_messageInfo_Verify.Size(m)
}
func (m *Verify) XXX_DiscardUnknown() {
	xxx_messageInfo_Verify.DiscardUnknown(m)
}

var xxx_messageInfo_Verify proto.InternalMessageInfo

func (m *Verify) GetVertices() []string {
	if m != nil {
		return m.Vertices
	}
	return nil
}

func (m *Verify) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterType((*Void)(nil), "protos.Void")
	proto.RegisterType((*UpdateValue)(nil), "protos.UpdateValue")
	proto.RegisterType((*Verify)(nil), "protos.Verify")
}

func init() { proto.RegisterFile("replica.proto", fileDescriptor_1e84aa831fb48ea1) }

var fileDescriptor_1e84aa831fb48ea1 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xc9, 0x5f, 0x91, 0x2b, 0x54, 0xe8, 0x60, 0xb0, 0x3a, 0x45, 0x99, 0xb2, 0x50, 0x21,
	0xe0, 0x0b, 0x20, 0xba, 0x74, 0x43, 0x41, 0x64, 0x37, 0xee, 0x01, 0x56, 0xa2, 0xda, 0xba, 0x98,
	0xa0, 0x7e, 0x7b, 0x14, 0x9b, 0x46, 0xa8, 0x93, 0xef, 0xfd, 0xee, 0x3d, 0xcb, 0xcf, 0x70, 0xc9,
	0x64, 0x7b, 0xad, 0xe4, 0xda, 0xb2, 0x71, 0x06, 0x73, 0x7f, 0x0c, 0x55, 0x0e, 0x69, 0x6b, 0xf4,
	0xae, 0x32, 0xb0, 0x78, 0xb3, 0x3b, 0xe9, 0xa8, 0x95, 0xfd, 0x37, 0xe1, 0x15, 0x24, 0x1d, 0x1d,
	0x44, 0x54, 0x46, 0x75, 0xd1, 0x4c, 0x23, 0xde, 0x40, 0x36, 0x4e, 0x2b, 0x11, 0x7b, 0x16, 0x04,
	0x22, 0xa4, 0x96, 0x69, 0x14, 0x89, 0x87, 0x7e, 0x9e, 0x9c, 0xaa, 0x37, 0xaa, 0x13, 0x69, 0x19,
	0xd5, 0x59, 0x13, 0x04, 0x2e, 0x21, 0xde, 0x6e, 0x44, 0xe6, 0x51, 0xbc, 0xdd, 0x54, 0x8f, 0x90,
	0xb7, 0xc4, 0xfa, 0xe3, 0x80, 0x2b, 0x38, 0x1f, 0x89, 0x9d, 0x56, 0x34, 0x88, 0xa8, 0x4c, 0xea,
	0xa2, 0x99, 0xf5, 0x5f, 0x2a, 0x3e, 0xa6, 0xee, 0xf7, 0xb0, 0x78, 0xfe, 0x92, 0xee, 0x95, 0x78,
	0xd4, 0x8a, 0xf0, 0x0e, 0x8a, 0x17, 0x36, 0xd6, 0x7c, 0x4a, 0x47, 0x78, 0x1d, 0xaa, 0x0d, 0xeb,
	0x7f, 0x45, 0x56, 0x17, 0x47, 0xe8, 0x5b, 0x9e, 0xe1, 0xed, 0x74, 0x01, 0xa9, 0xee, 0x69, 0x3f,
	0xfc, 0x10, 0xe3, 0x72, 0x5e, 0xfb, 0xb7, 0x9c, 0xda, 0xdf, 0xc3, 0x37, 0x3d, 0xfc, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x70, 0x8d, 0x12, 0x15, 0x3e, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	Propogate(ctx context.Context, in *UpdateValue, opts ...grpc.CallOption) (*Void, error)
	CheckAnswer(ctx context.Context, in *Verify, opts ...grpc.CallOption) (*Void, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Propogate(ctx context.Context, in *UpdateValue, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/protos.ChatService/Propogate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) CheckAnswer(ctx context.Context, in *Verify, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/protos.ChatService/CheckAnswer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	Propogate(context.Context, *UpdateValue) (*Void, error)
	CheckAnswer(context.Context, *Verify) (*Void, error)
}

// UnimplementedChatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (*UnimplementedChatServiceServer) Propogate(ctx context.Context, req *UpdateValue) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Propogate not implemented")
}
func (*UnimplementedChatServiceServer) CheckAnswer(ctx context.Context, req *Verify) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAnswer not implemented")
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_Propogate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).Propogate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ChatService/Propogate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).Propogate(ctx, req.(*UpdateValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CheckAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Verify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CheckAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.ChatService/CheckAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CheckAnswer(ctx, req.(*Verify))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Propogate",
			Handler:    _ChatService_Propogate_Handler,
		},
		{
			MethodName: "CheckAnswer",
			Handler:    _ChatService_CheckAnswer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "replica.proto",
}
